version: '3'
services:
  kvp:
    image: parity/kvp:latest

    ports:
      - "127.0.0.1:30333:30333/tcp"
      - "127.0.0.1:9933:9933/tcp"
      - "127.0.0.1:9944:9944/tcp"
      - "127.0.0.1:9615:9615/tcp"

    volumes:
      - "kvp-data:/data"

    command: |
      --unsafe-rpc-external
      --unsafe-ws-external
      --rpc-cors all
      --prometheus-external

volumes:
  kvp-data:
