#!/bin/sh

set -e

action="$1"
config_file="/etc/default/kvp"

if [ "$action" = "configure" ]; then
  # Make user and group
  getent group kvp >/dev/null 2>&1 || addgroup --system kvp
  getent passwd kvp >/dev/null 2>&1 ||
    adduser --system --home /home/kvp --disabled-password \
    --ingroup kvp kvp
  if [ ! -e "$config_file" ]; then
    echo 'kvp_CLI_ARGS=""' > /etc/default/kvp
  fi
fi
